FROM ubuntu:22.04

# Prevent interactive prompts during apt install
ENV DEBIAN_FRONTEND=noninteractive
# Optional: Pre-set timezone to avoid tzdata prompts completely
ENV TZ=Asia/Taipei

# 更新套件列表並安裝編譯所需的基礎工具
RUN apt-get update && apt-get install -y --no-install-recommends \
    iputils-ping net-tools iproute2 \
    debhelper \
    build-essential \
    devscripts \
    libsystemd-dev \
    freeglut3-dev \
    libopengl-dev \
    git cmake python3 freeglut3-dev

# 可以根據你的套件需求安裝額外的依賴項
# 例如：
RUN apt-get install -y --no-install-recommends \
    qt5-qmake \
    qtbase5-dev \
    libqt5websockets5-dev \
    libqt5serialport5-dev \
    qtwebengine5-dev \
    qtbase5-private-dev \
    libqt5opengl5-dev

# 清理 apt 快取以減小映像檔大小 (可選)
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# 設定工作目錄（可選）
WORKDIR /media

# 將原始碼複製到容器中（如果你有原始碼）使用-v map volumn
# COPY . /build

# 定義編譯命令（這會在容器啟動時執行，但我們通常會在容器內手動執行）
# CMD ["debuild", "-us", "-uc", "-b"]
CMD ["bash"]
