#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_PATCH 202305
#define VERSION_BUILD 29

#define VERSION "VERSION_MAJOR.VERSION_MINOR.VERSION_PATCH.VERSION_BUILD"

#endif // VERSION_H
