#ifndef VERSIONS_H
#define VERSIONS_H

#ifndef QIPERF_VERSION
#define QIPERF_VERSION "0.7"
#endif
#ifndef QIPERFD_VERSION
#define QIPERFD_VERSION "0.7.11312.23"
#endif
#ifndef QIPERFC_VERSION
#define QIPERFC_VERSION "0.7.11312.23"
#endif
#ifndef QIPERFTRAY_VERSION
#define QIPERFTRAY_VERSION "0.7.11312.23"
#endif

#endif //VERSIONS_H
